# Generated by Django 6.0.7 on 2026-08-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interpretation", "0008_roominterpretation_language_streams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roominterpretation",
            name="status",
            field=models.CharField(
                choices=[("idle", "Idle"), ("running", "Running")],
                default="idle",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="roominterpretation",
            name="stream_url",
            field=models.URLField(
                blank=True,
                help_text="Stream URL that the interpreter will ingest (YouTube, HLS, Vimeo, …). Defaults from the room configuration when empty.",
                verbose_name="Stream URL",
            ),
        ),
    ]
