# Generated by Django 6.0.7 on 2026-08-18 15:27

import django.db.models.deletion
import eventyay.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interpretation", "0009_alter_roominterpretation_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoxbentoOAuthGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(blank=True, max_length=2048)),
                ("refresh_token", models.CharField(blank=True, max_length=2048)),
                ("scopes", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voxbento_oauth_grant",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "VoxBento OAuth Grant",
                "verbose_name_plural": "VoxBento OAuth Grants",
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
    ]
