# Generated by Django 6.0.7 on 2026-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0011_voxbento_webhooks_and_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='webhook_scope_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='webhook_subscription_failed',
            field=models.BooleanField(default=False),
        ),
    ]
