# Generated by Django 6.1 on 2026-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0015_voxbentooauthgrant_is_disconnected'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominterpretation',
            name='enable_transcription',
            field=models.BooleanField(default=False, verbose_name='Enable transcription'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='enable_translation',
            field=models.BooleanField(default=False, verbose_name='Enable translation'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='transcription_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Transcription model'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='translation_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Translation model'),
        ),
    ]
