# Generated by Django 6.0.7 on 2026-09-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0016_roominterpretation_enable_transcription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominterpretation',
            name='enable_transcription',
        ),
        migrations.RemoveField(
            model_name='roominterpretation',
            name='enable_translation',
        ),
        migrations.RemoveField(
            model_name='roominterpretation',
            name='transcription_model',
        ),
        migrations.RemoveField(
            model_name='roominterpretation',
            name='translation_model',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='deepgram_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='elevenlabs_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='nvidia_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='voxbentooauthgrant',
            name='translation_openai_api_key',
        ),
    ]
