# Generated by Django 6.0.7 on 2026-09-17 19:18

import interpretation.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0016_roominterpretation_enable_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='anthropic_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='deepgram_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='elevenlabs_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='gemini_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='groq_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='nvidia_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='openai_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='openrouter_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='translation_openai_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
