# Generated by Django 6.0.7 on 2026-10-01 07:07

import interpretation.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0017_remove_roominterpretation_enable_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominterpretation',
            name='enable_transcription',
            field=models.BooleanField(default=False, verbose_name='Enable transcription'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='enable_translation',
            field=models.BooleanField(default=False, verbose_name='Enable translation'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='transcription_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Transcription model'),
        ),
        migrations.AddField(
            model_name='roominterpretation',
            name='translation_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Translation model'),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='anthropic_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='deepgram_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='elevenlabs_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='gemini_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='groq_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='nvidia_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='openai_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='openrouter_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='translation_openai_api_key',
            field=interpretation.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
